---
title: 'Lab 4: Data cleaning with dplyr'
author: "Student Name"
date: "DATE"
output: html_document
---

```{r, warning=FALSE, message=FALSE}
library(nycflights13)
library(hflights)
library(dplyr)
```

# Basic 5 commands
For this exercise, at each step use the assignment operator `<-` to store the results into a new data table and use that data in the next step. You will use the `hflights` data set which is data on flights departing from two Houston airports in 2011. 

1. Use `select()` to extract the following variables:  `Distance`, and `AirTime`. 


2. Use `filter()` to select only the flights who traveled exactly 501 miles. 


3. Use `mutate()` to create a new variable `Speed` that calculates speed of the plane as Distance/AirTime*60.


4. Use `arrange()` to order the previous data frame by ascending `AirTime`. 


5. Use `slice()` to select the flight with the shortest time in the air. (_Hint: the shortest flight should be in row 1 after you sort by ascending AirTime_). How fast did this plane go? 



# Chaining Operations
Use dplyr functions and the pipe operator (` %>% `) to transform the following English sentences into R code:

1. Take the `hflights` data set and then ...
2. Add a variable named `diff` that is the result of subtracting `TaxiIn` from `TaxiOut`, and then ...
3. Pick all of the rows whose `diff` value does not equal `NA`, and then ...
4. Summarise the data set with a value named `avg` that is the mean diff value.  
5. Store the result in the variable `p`.
6. Print `p` to the screen. 

# Table Joins

1. Identify rainy days (days with more than 1 inch of rain) from the `weather` data set.

- Start with the `weather` data set and group by day (`year`, `month`, `day`)
- summarize the data to create a new variable that equals the `sum(precip)` 
- create an indicator variable called `rainday` for days with more than 1 inch of rain
    - The `ifelse()` function is helpful here.


2. Add the rainy day from the previous step onto flight delay data frame (`flights`) using a `left_join`. Use `select()` to only keep the the two variables of interest (`dep_delay`, `rainday`) on the resulting data set. 



3. Examine the distribution of the departure delays across rainy and non-rainy days.



4. Explain why there is a NA category.




5. Use `na.omit()` to drop all records from the data set created in #2 that contain any missing data.  **Save this as a new data object**



6. How many records were deleted due to missing data? Hint: You can use `NROW()` to count the number of rows (records) in a data set. 




7. Recreate your plot using the data without missing values and answer the original question

